#ifndef IVI_CLIENT_H
#define IVI_CLIENT_H

/* Generated with cbindgen:0.26.0 */

/* Warning: This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 C-compatible error codes
 */
typedef enum IviErrorCode {
    /*
     Operation succeeded
     */
    OK = 0,
    /*
     Connection to IVI controller failed
     */
    CONNECTION_FAILED = -1,
    /*
     JSON-RPC request failed
     */
    REQUEST_FAILED = -2,
    /*
     Serialization error
     */
    SERIALIZATION = -3,
    /*
     Deserialization error
     */
    DESERIALIZATION = -4,
    /*
     I/O error
     */
    IO = -5,
    /*
     Invalid parameter (null pointer, etc.)
     */
    INVALID_PARAM = -6,
} IviErrorCode;

/*
 C-compatible orientation enum
 */
typedef enum IviOrientation {
    NORMAL = 0,
    ROTATE90 = 1,
    ROTATE180 = 2,
    ROTATE270 = 3,
} IviOrientation;

/*
 Client for communicating with the Weston IVI controller.

 The `IviClient` maintains a connection to the IVI controller over a UNIX domain socket
 and provides methods for sending JSON-RPC requests and receiving responses.

 # Example

 ```no_run
 use ivi_client::IviClient;

 # fn main() -> ivi_client::Result<()> {
 let mut client = IviClient::connect("/tmp/weston-ivi-controller.sock")?;
 // Use the client to interact with the IVI controller
 client.disconnect()?;
 # Ok(())
 # }
 ```
 */
typedef struct IviClient IviClient;

/*
 C-compatible size structure
 */
typedef struct IviSize {
    uint32_t width;
    uint32_t height;
} IviSize;

/*
 C-compatible position structure
 */
typedef struct IviPosition {
    int32_t x;
    int32_t y;
} IviPosition;

/*
 C-compatible surface structure
 */
typedef struct IviSurface {
    uint32_t id;
    struct IviSize orig_size;
    struct IviPosition src_position;
    struct IviSize src_size;
    struct IviPosition dest_position;
    struct IviSize dest_size;
    bool visibility;
    float opacity;
    enum IviOrientation orientation;
    int32_t z_order;
} IviSurface;

/*
 C-compatible layer structure
 */
typedef struct IviLayer {
    uint32_t id;
    bool visibility;
    float opacity;
} IviLayer;

/*
 Connect to the IVI controller

 # Safety

 - `socket_path` must be a valid null-terminated C string or NULL
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL

 # Returns

 Returns a pointer to an IviClient on success, or NULL on failure.
 If NULL is returned, the error message is written to `error_buf`.
 */
struct IviClient *ivi_client_connect(const char *socket_path,
                                     char *error_buf,
                                     uintptr_t error_buf_len);

/*
 Disconnect from the IVI controller and free the client

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`, or NULL
 - After calling this function, `client` must not be used again
 */
void ivi_client_disconnect(struct IviClient *client);

/*
 List all surfaces

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `surfaces` must be a valid pointer to a pointer that will receive the array
 - `count` must be a valid pointer to receive the array length
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL

 # Returns

 Returns IviErrorCode::Ok on success, or an error code on failure.
 On success, `surfaces` points to an allocated array and `count` contains the array length.
 The caller must free the array using `ivi_free_surfaces`.
 */
enum IviErrorCode ivi_list_surfaces(struct IviClient *client,
                                    struct IviSurface **surfaces,
                                    uintptr_t *count,
                                    char *error_buf,
                                    uintptr_t error_buf_len);

/*
 Get properties of a specific surface

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `surface` must be a valid pointer to an IviSurface structure
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL

 # Returns

 Returns IviErrorCode::Ok on success, or an error code on failure.
 On success, `surface` is populated with the surface properties.
 */
enum IviErrorCode ivi_get_surface(struct IviClient *client,
                                  uint32_t id,
                                  struct IviSurface *surface,
                                  char *error_buf,
                                  uintptr_t error_buf_len);

/*
 Set surface position

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_surface_position(struct IviClient *client,
                                           uint32_t id,
                                           int32_t x,
                                           int32_t y,
                                           char *error_buf,
                                           uintptr_t error_buf_len);

/*
 Set surface size

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_surface_size(struct IviClient *client,
                                       uint32_t id,
                                       uint32_t width,
                                       uint32_t height,
                                       char *error_buf,
                                       uintptr_t error_buf_len);

/*
 Set surface visibility

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_surface_visibility(struct IviClient *client,
                                             uint32_t id,
                                             bool visible,
                                             char *error_buf,
                                             uintptr_t error_buf_len);

/*
 Set surface opacity

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_surface_opacity(struct IviClient *client,
                                          uint32_t id,
                                          float opacity,
                                          char *error_buf,
                                          uintptr_t error_buf_len);

/*
 Set surface orientation

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_surface_orientation(struct IviClient *client,
                                              uint32_t id,
                                              enum IviOrientation orientation,
                                              char *error_buf,
                                              uintptr_t error_buf_len);

/*
 Set surface z-order

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_surface_z_order(struct IviClient *client,
                                          uint32_t id,
                                          int32_t z_order,
                                          char *error_buf,
                                          uintptr_t error_buf_len);

/*
 Set surface focus

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_surface_focus(struct IviClient *client,
                                        uint32_t id,
                                        char *error_buf,
                                        uintptr_t error_buf_len);

/*
 List all layers

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `layers` must be a valid pointer to a pointer that will receive the array
 - `count` must be a valid pointer to receive the array length
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL

 # Returns

 Returns IviErrorCode::Ok on success, or an error code on failure.
 On success, `layers` points to an allocated array and `count` contains the array length.
 The caller must free the array using `ivi_free_layers`.
 */
enum IviErrorCode ivi_list_layers(struct IviClient *client,
                                  struct IviLayer **layers,
                                  uintptr_t *count,
                                  char *error_buf,
                                  uintptr_t error_buf_len);

/*
 Get properties of a specific layer

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `layer` must be a valid pointer to an IviLayer structure
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL

 # Returns

 Returns IviErrorCode::Ok on success, or an error code on failure.
 On success, `layer` is populated with the layer properties.
 */
enum IviErrorCode ivi_get_layer(struct IviClient *client,
                                uint32_t id,
                                struct IviLayer *layer,
                                char *error_buf,
                                uintptr_t error_buf_len);

/*
 Set layer visibility

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_layer_visibility(struct IviClient *client,
                                           uint32_t id,
                                           bool visible,
                                           char *error_buf,
                                           uintptr_t error_buf_len);

/*
 Set layer opacity

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_layer_opacity(struct IviClient *client,
                                        uint32_t id,
                                        float opacity,
                                        char *error_buf,
                                        uintptr_t error_buf_len);

/*
 Commit pending changes

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_commit(struct IviClient *client, char *error_buf, uintptr_t error_buf_len);

/*
 Free surfaces array allocated by ivi_list_surfaces

 # Safety

 - `surfaces` must be a pointer returned from `ivi_list_surfaces`, or NULL
 - `count` must be the same value that was returned by `ivi_list_surfaces`
 - After calling this function, `surfaces` must not be used again
 */
void ivi_free_surfaces(struct IviSurface *surfaces, uintptr_t count);

/*
 Free layers array allocated by ivi_list_layers

 # Safety

 - `layers` must be a pointer returned from `ivi_list_layers`, or NULL
 - `count` must be the same value that was returned by `ivi_list_layers`
 - After calling this function, `layers` must not be used again
 */
void ivi_free_layers(struct IviLayer *layers, uintptr_t count);

#endif /* IVI_CLIENT_H */
