#ifndef IVI_CLIENT_H
#define IVI_CLIENT_H

/* Generated with cbindgen:0.26.0 */

/* Warning: This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 C-compatible error codes
 */
typedef enum IviErrorCode {
    /*
     Operation succeeded
     */
    OK = 0,
    /*
     Connection to IVI controller failed
     */
    CONNECTION_FAILED = -1,
    /*
     JSON-RPC request failed
     */
    REQUEST_FAILED = -2,
    /*
     Serialization error
     */
    SERIALIZATION = -3,
    /*
     Deserialization error
     */
    DESERIALIZATION = -4,
    /*
     I/O error
     */
    IO = -5,
    /*
     Invalid parameter (null pointer, etc.)
     */
    INVALID_PARAM = -6,
} IviErrorCode;

/*
 Event type enum for C consumers.
 */
typedef enum IviEventType {
    SURFACE_CREATED = 0,
    SURFACE_DESTROYED = 1,
    SOURCE_GEOMETRY_CHANGED = 2,
    DESTINATION_GEOMETRY_CHANGED = 3,
    VISIBILITY_CHANGED = 4,
    OPACITY_CHANGED = 5,
    ORIENTATION_CHANGED = 6,
    Z_ORDER_CHANGED = 7,
    FOCUS_CHANGED = 8,
    LAYER_CREATED = 9,
    LAYER_DESTROYED = 10,
    LAYER_VISIBILITY_CHANGED = 11,
    LAYER_OPACITY_CHANGED = 12,
    SURFACE_CONTENT_READY = 13,
    SURFACE_CONTENT_SIZE_CHANGED = 14,
} IviEventType;

/*
 Indicates whether a notification refers to a surface or a layer.
 */
typedef enum IviObjectType {
    SURFACE = 0,
    LAYER = 1,
} IviObjectType;

/*
 C-compatible orientation enum
 */
typedef enum IviOrientation {
    NORMAL = 0,
    ROTATE90 = 1,
    ROTATE180 = 2,
    ROTATE270 = 3,
    FLIPPED = 4,
    FLIPPED90 = 5,
    FLIPPED180 = 6,
    FLIPPED270 = 7,
} IviOrientation;

typedef struct IviClient IviClient;

/*
 Listens for event notifications from the IVI controller.

 Opens its own dedicated socket connection so that notifications are not
 mixed with RPC responses on the shared `IviClient` connection.

 # Example

 ```no_run
 use ivi_client::{NotificationListener, EventType};

 # fn main() -> ivi_client::Result<()> {
 let mut listener = NotificationListener::new(None)?;

 listener.on(EventType::SurfaceCreated, |notif| {
     println!("Surface created: {}", notif.params["surface_id"]);
 });

 listener.on_all(|notif| {
     println!("Event: {:?}", notif.event_type);
 });

 listener.start(&[EventType::SurfaceCreated, EventType::VisibilityChanged])?;
 // ... callbacks fire in background thread ...
 listener.stop();
 # Ok(())
 # }
 ```
 */
typedef struct NotificationListener NotificationListener;

typedef uint32_t SurfaceId;

typedef struct IviSize {
    int32_t width;
    int32_t height;
} IviSize;

typedef struct Rectangle {
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
} Rectangle;

/*
 C-compatible surface structure
 */
typedef struct IviSurface {
    SurfaceId id;
    struct IviSize orig_size;
    struct Rectangle src_rect;
    struct Rectangle dest_rect;
    bool visibility;
    float opacity;
    enum IviOrientation orientation;
    int32_t z_order;
} IviSurface;

typedef uint32_t LayerId;

/*
 C-compatible layer structure
 */
typedef struct IviLayer {
    LayerId id;
    struct Rectangle src_rect;
    struct Rectangle dest_rect;
    bool visibility;
    float opacity;
    enum IviOrientation orientation;
} IviLayer;

/*
 Visibility change data (old and new state).
 */
typedef struct IviVisibilityChange {
    bool old_visibility;
    bool new_visibility;
} IviVisibilityChange;

/*
 Opacity change data (old and new value).
 */
typedef struct IviOpacityChange {
    float old_opacity;
    float new_opacity;
} IviOpacityChange;

/*
 Geometry (rectangle) change data (old and new rectangle).
 */
typedef struct IviGeometryChange {
    struct Rectangle old_rect;
    struct Rectangle new_rect;
} IviGeometryChange;

/*
 Z-order change data (old and new value).
 */
typedef struct IviZOrderChange {
    int32_t old_z_order;
    int32_t new_z_order;
} IviZOrderChange;

/*
 Orientation change data (old and new value).
 */
typedef struct IviOrientationChange {
    enum IviOrientation old_orientation;
    enum IviOrientation new_orientation;
} IviOrientationChange;

/*
 Content ready data: buffer dimensions when the first frame is committed.
 */
typedef struct IviContentReadyInfo {
    int32_t width;
    int32_t height;
} IviContentReadyInfo;

/*
 Content size change data: old and new buffer dimensions.
 */
typedef struct IviContentSizeChange {
    int32_t old_width;
    int32_t old_height;
    int32_t new_width;
    int32_t new_height;
} IviContentSizeChange;

/*
 A notification event delivered to C callbacks.

 Only the fields relevant to `event_type` are populated; all others are
 zero-initialised. Check `object_type` to determine whether `object_id`
 refers to a surface or a layer.

 For `FocusChanged` events:
   - `object_type`   = `SURFACE`
   - `object_id`     = new focused surface ID (0 if none)
   - `object_old_id` = previous focused surface ID (0 if none)
 */
typedef struct IviNotification {
    enum IviEventType event_type;
    enum IviObjectType object_type;
    /*
     Current object ID (surface or layer). For focus events: new focused surface.
     */
    uint32_t object_id;
    /*
     Previous object ID. Only meaningful for `FocusChanged` events.
     */
    uint32_t object_old_id;
    struct IviVisibilityChange visibility;
    struct IviOpacityChange opacity;
    struct IviGeometryChange src_geometry;
    struct IviGeometryChange dest_geometry;
    struct IviZOrderChange z_order;
    struct IviOrientationChange orientation;
    struct IviContentReadyInfo content_ready;
    struct IviContentSizeChange content_size;
} IviNotification;

/*
 C callback type for notification events.
 */
typedef void (*IviNotificationCCallback)(const struct IviNotification *notif, void *user_data);

/*
 Connect to the IVI controller

 # Safety

 - `socket_path` must be a valid null-terminated C string or NULL
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL

 # Returns

 Returns a pointer to an IviClient on success, or NULL on failure.
 If NULL is returned, the error message is written to `error_buf`.
 */
struct IviClient *ivi_client_connect(const char *remote, char *error_buf, uintptr_t error_buf_len);

/*
 Disconnect from the IVI controller and free the client

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`, or NULL
 - After calling this function, `client` must not be used again
 */
void ivi_client_disconnect(struct IviClient *client);

/*
 List all surfaces

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `surfaces` must be a valid pointer to a pointer that will receive the array
 - `count` must be a valid pointer to receive the array length
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL

 # Returns

 Returns IviErrorCode::Ok on success, or an error code on failure.
 On success, `surfaces` points to an allocated array and `count` contains the array length.
 The caller must free the array using `ivi_free_surfaces`.
 */
enum IviErrorCode ivi_list_surfaces(struct IviClient *client,
                                    struct IviSurface **surfaces,
                                    uintptr_t *count,
                                    char *error_buf,
                                    uintptr_t error_buf_len);

/*
 Get properties of a specific surface

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `surface` must be a valid pointer to an IviSurface structure
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL

 # Returns

 Returns IviErrorCode::Ok on success, or an error code on failure.
 On success, `surface` is populated with the surface properties.
 */
enum IviErrorCode ivi_get_surface(struct IviClient *client,
                                  uint32_t id,
                                  struct IviSurface *surface,
                                  char *error_buf,
                                  uintptr_t error_buf_len);

/*
 Set surface source rectangle (which part of buffer to display)

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_surface_source_rectangle(struct IviClient *client,
                                                   uint32_t id,
                                                   int32_t x,
                                                   int32_t y,
                                                   int32_t width,
                                                   int32_t height,
                                                   char *error_buf,
                                                   uintptr_t error_buf_len);

/*
 Set surface destination rectangle (where and how to display on screen)

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_surface_destination_rectangle(struct IviClient *client,
                                                        uint32_t id,
                                                        int32_t x,
                                                        int32_t y,
                                                        int32_t width,
                                                        int32_t height,
                                                        char *error_buf,
                                                        uintptr_t error_buf_len);

/*
 Set surface visibility

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_surface_visibility(struct IviClient *client,
                                             uint32_t id,
                                             bool visible,
                                             char *error_buf,
                                             uintptr_t error_buf_len);

/*
 Set surface opacity

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_surface_opacity(struct IviClient *client,
                                          uint32_t id,
                                          float opacity,
                                          char *error_buf,
                                          uintptr_t error_buf_len);

/*
 Set surface z-order

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_surface_z_order(struct IviClient *client,
                                          uint32_t id,
                                          int32_t z_order,
                                          char *error_buf,
                                          uintptr_t error_buf_len);

/*
 Set surface focus

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_surface_focus(struct IviClient *client,
                                        uint32_t id,
                                        char *error_buf,
                                        uintptr_t error_buf_len);

/*
 List all layers

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `layers` must be a valid pointer to a pointer that will receive the array
 - `count` must be a valid pointer to receive the array length
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL

 # Returns

 Returns IviErrorCode::Ok on success, or an error code on failure.
 On success, `layers` points to an allocated array and `count` contains the array length.
 The caller must free the array using `ivi_free_layers`.
 */
enum IviErrorCode ivi_list_layers(struct IviClient *client,
                                  struct IviLayer **layers,
                                  uintptr_t *count,
                                  char *error_buf,
                                  uintptr_t error_buf_len);

/*
 Get properties of a specific layer

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `layer` must be a valid pointer to an IviLayer structure
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL

 # Returns

 Returns IviErrorCode::Ok on success, or an error code on failure.
 On success, `layer` is populated with the layer properties.
 */
enum IviErrorCode ivi_get_layer(struct IviClient *client,
                                uint32_t id,
                                struct IviLayer *layer,
                                char *error_buf,
                                uintptr_t error_buf_len);

/*
 Set layer visibility

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_layer_visibility(struct IviClient *client,
                                           uint32_t id,
                                           bool visible,
                                           char *error_buf,
                                           uintptr_t error_buf_len);

/*
 Set layer opacity

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_layer_opacity(struct IviClient *client,
                                        uint32_t id,
                                        float opacity,
                                        char *error_buf,
                                        uintptr_t error_buf_len);

/*
 Set layer source rectangle

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_layer_source_rectangle(struct IviClient *client,
                                                 uint32_t id,
                                                 int32_t x,
                                                 int32_t y,
                                                 int32_t width,
                                                 int32_t height,
                                                 char *error_buf,
                                                 uintptr_t error_buf_len);

/*
 Set layer destination rectangle

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_set_layer_destination_rectangle(struct IviClient *client,
                                                      uint32_t id,
                                                      int32_t x,
                                                      int32_t y,
                                                      int32_t width,
                                                      int32_t height,
                                                      char *error_buf,
                                                      uintptr_t error_buf_len);

/*
 Commit pending changes

 # Safety

 - `client` must be a valid pointer returned from `ivi_client_connect`
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_commit(struct IviClient *client, char *error_buf, uintptr_t error_buf_len);

/*
 Free surfaces array allocated by ivi_list_surfaces

 # Safety

 - `surfaces` must be a pointer returned from `ivi_list_surfaces`, or NULL
 - `count` must be the same value that was returned by `ivi_list_surfaces`
 - After calling this function, `surfaces` must not be used again
 */
void ivi_free_surfaces(struct IviSurface *surfaces, uintptr_t count);

/*
 Free layers array allocated by ivi_list_layers

 # Safety

 - `layers` must be a pointer returned from `ivi_list_layers`, or NULL
 - `count` must be the same value that was returned by `ivi_list_layers`
 - After calling this function, `layers` must not be used again
 */
void ivi_free_layers(struct IviLayer *layers, uintptr_t count);

/*
 Create a notification listener with its own connection to the IVI controller.

 # Safety

 - `socket_path` must be a valid null-terminated C string or NULL
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL

 # Returns

 Returns a pointer to a `NotificationListener` on success, or NULL on failure.
 */
struct NotificationListener *ivi_notification_listener_new(const char *socket_path,
                                                           char *error_buf,
                                                           uintptr_t error_buf_len);

/*
 Stop and free a notification listener.

 # Safety

 - `listener` must be a valid pointer returned from `ivi_notification_listener_new`, or NULL
 - After calling this function, `listener` must not be used again
 */
void ivi_notification_listener_free(struct NotificationListener *listener);

/*
 Register a C callback for a specific event type.

 Multiple callbacks per event type are allowed.

 # Safety

 - `listener` must be a valid pointer returned from `ivi_notification_listener_new`
 - `callback` must remain valid for the lifetime of the listener
 - `user_data` is passed to the callback as-is; the caller is responsible for its lifetime
 */
enum IviErrorCode ivi_notification_listener_on(struct NotificationListener *listener,
                                               enum IviEventType event_type,
                                               IviNotificationCCallback callback,
                                               void *user_data);

/*
 Register a C catch-all callback invoked for every event type.

 # Safety

 - `listener` must be a valid pointer returned from `ivi_notification_listener_new`
 - `callback` must remain valid for the lifetime of the listener
 - `user_data` is passed to the callback as-is; the caller is responsible for its lifetime
 */
enum IviErrorCode ivi_notification_listener_on_all(struct NotificationListener *listener,
                                                   IviNotificationCCallback callback,
                                                   void *user_data);

/*
 Subscribe to the specified event types and start the background reader thread.

 # Safety

 - `listener` must be a valid pointer returned from `ivi_notification_listener_new`
 - `event_types` must be a valid pointer to an array of `count` `IviEventType` values, or NULL
   if `count` is 0
 - `error_buf` must be a valid pointer to a buffer of at least `error_buf_len` bytes, or NULL
 */
enum IviErrorCode ivi_notification_listener_start(struct NotificationListener *listener,
                                                  const enum IviEventType *event_types,
                                                  uintptr_t count,
                                                  char *error_buf,
                                                  uintptr_t error_buf_len);

/*
 Stop the background reader thread. Registered callbacks will no longer fire.

 # Safety

 - `listener` must be a valid pointer returned from `ivi_notification_listener_new`
 */
void ivi_notification_listener_stop(struct NotificationListener *listener);

#endif /* IVI_CLIENT_H */
